function arr2obj(arr) {
  let obj = {};
  arr.map(
    (songName) =>
      (obj[songName] = {
        length: 3,
        vocals: true,
        quiet: true,
        banger: true,
        wellknown: true,
        year: 2006,
        dirty: false,
      })
  );
  return obj;
}

let songs = [
  "Put You Records On",
  "Sell Out",
  "Video Killed The Radio Star",
  "Move Your Feet",
  "I Want You Back",
  "Toxic",
  "Livin' La Vida Loca",
  "AP Touro",
  "Tears Dry On Their Own",
  "Pencil Full Of Lead",
  "Don't You Want Me",
  "It Must Be Love",
  "Sweet Dreams Are Made Of This",
  "Grease",
  "Smooth",
  "Ain't Got No – I Got Life",
  "Blame It On The Boogie",
  "Gibbous",
  "Hello",
  "I Feel Good",
  "Walking On Sunshine",
  "Brown Eyed Girl",
  "Crazy In Love",
  "Ten Out Of Ten",
  "You Can Call Me Al",
  "Build Me Up Buttercup",
  "Can't Get You Out Of My Head",
  "Thrift Shop",
  "Can't Take My Eyes Off You",
  "Higher and Higher",
  "She Has A Girlfriend Now",
  "Man I Feel Like A Woman",
  "You Are The Best Thing",
  "I'm Coming Out",
  "Sax",
  "Forget You",
  "My Type",
  "Twist and Shout",
  "Shut Up and Dance",
  "Take On Me",
  "Livin on a Prayer",
  "Mr Brightside",
  "Love Never Felt So Good",
  "Come On Eileen",
  "Redbone",
  "Stacy's Mom",
  "Treasure",
  "Lean On",
  "Son Of A Preacher Man",
  "Cake by the Ocean",
  "Escape (Pina Colada Song)",
  "We Built This City",
  "Titanium",
  "9 to 5",
  "Bad Guy",
  "Fuck You (Lily Allen)",
  "Mr Blue Sky",
  "Oh What A Night",
  "Ride",
  "Tu Vuo Fa l'Americano",
  "This Girl",
  "Take Me Out",
  "Rude",
  "Five Colours In Her Hair",
  "Think About Things",
  "Blinding Lights",
  "Closer",
  "Take You Dancing",
  "Don't Start Now",
  "Gimme Gimme Gimme",
  "All I Want For Christmas Is You",
  "It's Raining Men",
  "I Will Survive",
];

arr2obj(songs);
