const BANGER_LEVEL = {
  topBanger: 1,
  decentBanger: 0.8,
  solidChoice: 0.6,
  bitRogue: 0.4,
  obscure: 0.2,
};

const DIRTY_LEVEL = {
  filthy: -1,
  questionable: 0.2,
  wholesome: 1,
};

export const songs = {
  "Put You Records On": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Sell Out": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Video Killed The Radio Star": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Move Your Feet": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.questionable,
  },
  "I Want You Back": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Toxic: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Livin' La Vida Loca": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.questionable,
  },
  "AP Touro": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: BANGER_LEVEL.obscure,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Tears Dry On Their Own": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Pencil Full Of Lead": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Don't You Want Me": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "It Must Be Love": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Sweet Dreams Are Made Of This": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Grease: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Smooth: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Ain't Got No – I Got Life": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Blame It On The Boogie": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Gibbous: {
    length: 3,
    vocals: false,
    quiet: false,
    banger: BANGER_LEVEL.obscure,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Hello: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.obscure,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.filthy,
  },
  "I Feel Good": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Walking On Sunshine": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Brown Eyed Girl": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Crazy In Love": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Ten Out Of Ten": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "You Can Call Me Al": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Build Me Up Buttercup": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Can't Get You Out Of My Head": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Thrift Shop": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Can't Take My Eyes Off You": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Higher and Higher": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "She Has A Girlfriend Now": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Man I Feel Like A Woman": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.questionable,
  },
  "You Are The Best Thing": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.obscure,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "I'm Coming Out": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2006,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Sax: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: false,
    year: 2006,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Forget You": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2010,
    dirty: DIRTY_LEVEL.filthy,
  },
  "My Type": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2014,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Twist and Shout": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1964,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Shut Up and Dance": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2014,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Take On Me": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1984,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Livin on a Prayer": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1986,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Mr Brightside": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2003,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Love Never Felt So Good": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: false,
    year: 2014,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Come On Eileen": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1982,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Redbone: {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: false,
    year: 2016,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Stacy's Mom": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2003,
    dirty: DIRTY_LEVEL.filthy,
  },
  Treasure: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2013,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Lean On": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2015,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Son Of A Preacher Man": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 1968,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Cake by the Ocean": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2015,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Escape (Pina Colada Song)": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 1979,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "We Built This City": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 1985,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Titanium: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2011,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "9 to 5": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1980,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Bad Guy": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2019,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Fuck You (Lily Allen)": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: false,
    year: 2009,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Mr Blue Sky": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1978,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Oh What A Night": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 1975,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Ride: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: false,
    year: 2015,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Tu Vuo Fa l'Americano": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2010,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "This Girl": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2009,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Take Me Out": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2004,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Rude: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2013,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Five Colours In Her Hair": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2004,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Think About Things": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2020,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Blinding Lights": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2019,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Closer: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2016,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Take You Dancing": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2020,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Don't Start Now": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2019,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Gimme Gimme Gimme": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1979,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "All I Want For Christmas Is You": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1994,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "It's Raining Men": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1982,
    dirty: DIRTY_LEVEL.questionable,
  },
  "I Will Survive": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1978,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Back To Black": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2007,
    dirty: DIRTY_LEVEL.questionable,
  },
  Tragedy: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1978,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Vengabus: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1998,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Hava Nagila": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 1918,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Rasputin: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1978,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Voulez-Vous": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1979,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Come and Get Your Love": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 1974,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Ballroom Blitz": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.bitRogue,
    wellknown: true,
    year: 1973,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Wonderful Tonight": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.obscure,
    wellknown: true,
    year: 1977,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "99 Luftballons": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1983,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "I Wanna Dance With Somebody": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1987,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Shregamix: {
    length: 7,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2001,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Don't Speak": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1996,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Cuff It": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 2022,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Love Machine": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 2004,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Watermelon Sugar": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2019,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Paradise: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2018,
    dirty: DIRTY_LEVEL.wholesome,
  },
  XS: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: false,
    year: 2020,
    dirty: DIRTY_LEVEL.questionable,
  },
  Arthur: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2000,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Killing Me Softly": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: BANGER_LEVEL.solidChoice,
    wellknown: true,
    year: 1973,
    dirty: DIRTY_LEVEL.wholesome,
  },
  Barbie: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.topBanger,
    wellknown: true,
    year: 1997,
    dirty: DIRTY_LEVEL.questionable,
  },
  Kiss: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1986,
    dirty: DIRTY_LEVEL.questionable,
  },
  "Sreep & Mreep": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2010,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Tiggle Diggle Tiggle Miggle": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2013,
    dirty: DIRTY_LEVEL.filthy,
  },
  "Tracy Beaker's Dilemma": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2002,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Everlasting Love": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 1975,
    dirty: DIRTY_LEVEL.wholesome,
  },
  "Murder on the Dancefloor": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: BANGER_LEVEL.decentBanger,
    wellknown: true,
    year: 2001,
    dirty: DIRTY_LEVEL.wholesome,
  },
};

// export const total_num_songs = Object.keys(songs).length;
// does each song need a probability key?
