const songs = {
  "Put You Records On": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Sell Out": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: false,
  },
  "Video Killed The Radio Star": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Move Your Feet": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "I Want You Back": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  Toxic: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Livin' La Vida Loca": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "AP Touro": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: false,
  },
  "Tears Dry On Their Own": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: true,
  },
  "Pencil Full Of Lead": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: false,
  },
  "Don't You Want Me": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "It Must Be Love": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Sweet Dreams Are Made Of This": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  Grease: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: false,
  },
  Smooth: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: false,
  },
  "Ain't Got No – I Got Life": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Blame It On The Boogie": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  Gibbous: {
    length: 3,
    vocals: false,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: false,
  },
  Hello: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: true,
  },
  "I Feel Good": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Walking On Sunshine": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Brown Eyed Girl": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Crazy In Love": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: true,
  },
  "Ten Out Of Ten": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: false,
  },
  "You Can Call Me Al": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Build Me Up Buttercup": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Can't Get You Out Of My Head": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Thrift Shop": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: true,
  },
  "Can't Take My Eyes Off You": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "Higher and Higher": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "She Has A Girlfriend Now": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: true,
  },
  "Man I Feel Like A Woman": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  "You Are The Best Thing": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: false,
    wellknown: false,
    year: 2006,
    dirty: false,
  },
  "I'm Coming Out": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2006,
    dirty: false,
  },
  Sax: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: false,
    year: 2006,
    dirty: true,
  },
  "Forget You": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2010,
    dirty: true,
  },
  "My Type": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 2014,
    dirty: false,
  },
  "Twist and Shout": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 1964,
    dirty: false,
  },
  "Shut Up and Dance": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2014,
    dirty: false,
  },
  "Take On Me": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1984,
    dirty: false,
  },
  "Livin on a Prayer": {
    length: 3,
    vocals: false,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1986,
    dirty: false,
  },
  "Mr Brightside": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2003,
    dirty: true,
  },
  "Love Never Felt So Good": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2014,
    dirty: false,
  },
  "Come On Eileen": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1982,
    dirty: false,
  },
  Redbone: {
    length: 3,
    vocals: true,
    quiet: true,
    banger: false,
    wellknown: false,
    year: 2016,
    dirty: false,
  },
  "Stacy's Mom": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2003,
    dirty: true,
  },
  Treasure: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2013,
    dirty: false,
  },
  "Lean On": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2015,
    dirty: false,
  },
  "Son Of A Preacher Man": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: false,
    wellknown: true,
    year: 1968,
    dirty: false,
  },
  "Cake by the Ocean": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2015,
    dirty: true,
  },
  "Escape (Pina Colada Song)": {
    length: 3,
    vocals: true,
    quiet: true,
    banger: false,
    wellknown: true,
    year: 1979,
    dirty: false,
  },
  "We Built This City": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: true,
    year: 1985,
    dirty: false,
  },
  Titanium: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2011,
    dirty: false,
  },
  "9 to 5": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1980,
    dirty: false,
  },
  "Bad Guy": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2019,
    dirty: true,
  },
  "Fuck You (Lily Allen)": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: false,
    wellknown: false,
    year: 2009,
    dirty: true,
  },
  "Mr Blue Sky": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1978,
    dirty: false,
  },
  "Oh What A Night": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1975,
    dirty: false,
  },
  Ride: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: false,
    year: 2015,
    dirty: false,
  },
  "Tu Vuo Fa l'Americano": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2010,
    dirty: false,
  },
  "This Girl": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2009,
    dirty: false,
  },
  "Take Me Out": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2004,
    dirty: false,
  },
  Rude: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2013,
    dirty: false,
  },
  "Five Colours In Her Hair": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2004,
    dirty: false,
  },
  "Think About Things": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2020,
    dirty: false,
  },
  "Blinding Lights": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2019,
    dirty: false,
  },
  Closer: {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2016,
    dirty: false,
  },
  "Take You Dancing": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2020,
    dirty: false,
  },
  "Don't Start Now": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 2019,
    dirty: false,
  },
  "Gimme Gimme Gimme": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1979,
    dirty: false,
  },
  "All I Want For Christmas Is You": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1994,
    dirty: false,
  },
  "It's Raining Men": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1982,
    dirty: false,
  },
  "I Will Survive": {
    length: 3,
    vocals: true,
    quiet: false,
    banger: true,
    wellknown: true,
    year: 1978,
    dirty: false,
  },
};
